name: tests

on: push

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres
  POSTGRES_DB: rf_dados_publicos_cnpj
  POSTGRES_PORT: 5432

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        id: checkout

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: build img
        run: make build-img

      - name: create local env file
        run: |
          touch .env
          echo POSTGRES_USER=${{ env.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_HOST=${{ env.POSTGRES_HOST }} >> .env
          echo POSTGRES_DB=${{ env.POSTGRES_DB }} >> .env
          echo POSTGRES_PORT=${{ env.POSTGRES_PORT }} >> .env

      - name: run tests
        run: make tests
